[build]
builder = "nixpacks"
# Use a more reliable installation command
buildCommand = "npm cache clean --force && npm install --no-fund --no-audit --omit=dev"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3